-- MySQL Script generated by MySQL Workbench
-- Fri Dec 16 17:29:48 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dbp6
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `test` ;

-- -----------------------------------------------------
-- Schema dbp6
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `test` ;

-- -----------------------------------------------------
-- Table `dbp6`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test`.`user` ;

CREATE TABLE IF NOT EXISTS `test`.`user` (
    `id_user` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(45) NOT NULL,
    `username` VARCHAR(45) NOT NULL,
    `email` VARCHAR(45) NOT NULL,
    `password` VARCHAR(100) NOT NULL,
    `roles` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id_user`))
ENGINE = InnoDB;

DROP TABLE IF EXISTS `test`.`role` ;

CREATE TABLE IF NOT EXISTS `test`.`role` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- user_role
DROP TABLE IF EXISTS `test`.`user_role` ;

CREATE TABLE IF NOT EXISTS `test`.`user_role` (
   `user_id_user` INT NOT NULL,
   `role_id_role` INT NOT NULL,
   PRIMARY KEY (`user_id_user`, `role_id_role`),
    INDEX `fk_user_has_role_role1_idx` (`role_id_role` ASC) VISIBLE,
    INDEX `fk_user_has_user_user1_idx` (`user_id_user` ASC) VISIBLE,
    CONSTRAINT `fk_user_has_user_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `test`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_user_has_role_role1`
    FOREIGN KEY (`role_id_role`)
    REFERENCES `test`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

